.TH UNIXCLIENT 1
.SH NAME
unixclient - UNIX domain socket client
.SH SYNOPSIS
.B unixclient
.I socket program
.SH DESCRIPTION
.B unixclient
attempts to connect to a UNIX domain server.
The server's address is given by
.I socket
which is the filesystem path to the socket the server has created.
If it is successful, it runs
.I program
with file descriptor 6 reading from the socket and descriptor 7 writing to the socket.
.P
.SH SEE ALSO
unixserver(1),
unixcat(1),
http://cr.yp.to/proto/ucspi.txt
.SH AUTHOR
ucspi-unix package was written by Bruce Guenter <bruce@untroubled.org>
